title: Blog de Luciano
email: lucianoitaliani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mi nombre es Luciano Italiani y este es mi blog donde escribo
  todos mis proyectos relacionados con programacion y electronica.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: luchit09
github_username:  lucianoitaliani

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
include:
  - image
exclude:
  - config.ru
  - vendor
  - Gemfile
  - Gemfile.lock
